api_platform:
    title: 'NeoPixel Block REST API'
    description: 'NeoPixel Block'
    version: '0.0.1'
    mapping:
        paths: ['%kernel.project_dir%/src/Entity']
    patch_formats:
        json: ['application/merge-patch+json']
    swagger:
        versions: [3]
